config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pizzas
  root 'pizzas#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :pizzas
end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
    belongs_to :user
    belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pizzas
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
    before_action :find_pizza, only: [:show, :edit, :update, :destroy]
    
    def index
        if params[:category].blank?
            @pizzas = Pizza.all.order("created_at DESC")
        else
            @category_id = Category.find_by(name: params[:category]).id
            @pizzas = Pizza.where(:category_id => @category_id).order("created_at DESC")
        end
    end
    
    def show
    end
    
    def new
        @pizza = current_user.pizzas.build
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end
    
    def create
        
        @pizza = current_user.pizzas.build(pizza_params)
        @pizza.category_id = params[:category_id]
        
        if @pizza.save
            redirect_to root_path
        else
            render 'new'
        end
        
    end
    
    def edit
        @categories = Category.all.map{ |c| [c.name, c.id] }
    end
    
    def update
        @pizza.category_id = params[:category_id]
        if @pizza.update(pizza_params)
            redirect_to pizza_path(@pizza)
        else
            render  'edit'
        end
    end
    
    def destroy
        @pizza.destroy
        redirect_to root_path
    end
    
    private
    
    def pizza_params
        params.require(:pizza).permit(:title, :description, :author, :category_id)
    end
    
    def find_pizza
        @pizza = Pizza.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="navbar navbar-default">
    <div class="container">
      
      <div class "navbar-header">
        <%= link_to "Pizza Review", root_path, class: "navbar-brand" %>
      </div>
      
      <ul class="nav navbar-nav">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class"caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name %>">
                <%= link_to category.name, pizzas_path(category: category.name), class: "link" %>
              </li>
            <% end %>
          </ul>
        </li>
        
        <% if user_signed_in? %>
          <li><%= link_to "Add Pizza", new_pizza_path %></li>
        <% end %>
      </ul>
    </div>
    
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/pizzas/_form.html.erb
<%= simple_form_for @pizza, :html => { :multipart => true } do |f| %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select ad category") %>
    <%= f.input :title, label: "Pizza Name" %>
    <%= f.input :description %>
    <%= f.input  :author %>
    <%= f.button :submit %>
<% end %>

app/views/pizzas/edit.html.erb
<h1>Edit Pizza</h1>

<%= simple_form_for @pizza, :html => { :multipart => true } do |f| %>
    <%= f.select :category_id, @categories %>
    <%= f.input :title, label: "Pizza Name" %>
    <%= f.input :description %>
    <%= f.input  :author %>
    <%= f.button :submit %>
<% end %>

app/views/pizzas/index.html.erb
<h1 class="current_category"><%= params[:category] %></h1>

<% if @pizzas.count == 0 %>
    <h1>There are no Pizzas currently in this categroy</h1>
<% else %>
    <% @pizzas.each do |pizza| %>
        <h2><%= link_to pizza.title, pizza_path(pizza) %></h2>
    <% end %>
<% end %>

app/views/pizzas/new.html.erb
<h1>New Pizza</h1>

<%= render 'form' %>

app/views/pizzas/show.html.erb
<h2><%= @pizza.title %></h2>
<h3><%= @pizza.author %></h3>
<h4><%= @pizza.category.name %></h4>
<p><%= @pizza.description %></p>

<%= link_to "Back", root_path %>

<% if user_signed_in? %>

    <% if @pizza.user_id == current_user.id %>
    
        <%= link_to "Edit", edit_pizza_path(@pizza) %>
        <%= link_to "Delete", pizza_path(@pizza), method: :delete, data: { confirm: "Are you sure?" } %>
        
    <% end %>
    
<% end %>    